@extends('layouts.front')
@section('content')
  <div class="main">
    <div class="policy__container">
      <div class="rentalpolicy">
        <div class="policy__heading">
          <h1 class="policy__h1">RENTAL EXOTICS BEASTS PRIVACY POLICY</h1>
          <div class="policy__timestamp">Updated Aug 23, 2020</div>
          <div class="policy__note">*If you have any questions about these Terms of Use, please contact us at<br>
            {{ $setting->email }}.</div>
        </div> 
        <div class="policy__richtext w-richtext">
          <p>Rental exotics beasts operates the Rentalexoticsbeasts.com website (hereinafter referred to as the Service). This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data. We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from Rentalexoticsbeasts.</p>
          <h3>Definitions</h3>
          <h3>Service:</h3>
          <p>Service is the Rentalexoticsbeasts website operated by Rental exotics beasts.</p>
          <h3>Personal Data:</h3>
          <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
          <h3>Usage Data:</h3>
          <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
          <h3>Cookies:</h3>
          <p>Cookies are small files stored on your device (computer or mobile device).</p>
          <h3>Information Collection and Use:</h3>
          <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
          <h3>Types of Data Collected</h3>
          <h3>Personal Data::</h3>
          <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (Personal Data). Personally identifiable information may include, but is not limited to:

<br>Email address, First name and last name, Phone number.</p>
          <h3>Cookies and Usage Data:</h3>
          <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.</p>
          <h3>Usage Data:</h3>
          <p>We may also collect information on how the Service is accessed and used (Usage Data). This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
          
          <h3>Tracking & Cookies Data:</h3>
          <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
          <h3>Examples of Cookies we use:</h3>
          <p><span style="font-size:1.3em;">Session Cookies:</span> We use Session Cookies to operate our Service.<br>

          <span style="font-size:1.3em;">Preference Cookies:</span> We use Preference Cookies to remember your preferences and various settings.<br>

          <span style="font-size:1.3em;">Security Cookies:</span> We use Security Cookies for security purposes.</p>
          <h3>Use of Data</h3>
          <h3>Rental exotics beasts uses the collected data for various purposes:
</h3>
          <p>To provide and maintain our Service.<br>

To notify you about changes to our Service.<br>

To allow you to participate in interactive features of our Service when you choose to do so.<br>

To provide customer support To gather analysis or valuable information so that we can improve our Service.<br>

To monitor the usage of our Service To detect, prevent and address technical issues.<br>

To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.
</p>
          
          <h3>Transfer of Data:</h3>
          <p>Your information, including Personal Data, may be transferred to and maintained on computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. Rental exotics beasts will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
</p>
          <h3>Disclosure of Data</h3>
          <h3>Legal Requirements</h3>
          <p>Rental exotics beasts may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul>
            <li>
            To comply with a legal obligation.
            </li>
            <li>
            To protect and defend the rights or property of Rental exotics beasts To prevent or investigate possible wrongdoing in connection with the Service.

            </li>
            <li>
            To protect the personal safety of users of the Service or the public To protect against legal liability.
            </li>
            <li>
            Security of Data: 
The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.


            </li>
            <li>
            Service Providers: 
We may employ third party companies and individuals to facilitate our Service (Service Providers), provide the Service on our behalf, perform Service- related services or assist us in analyzing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
            </li>
            <li>
            Payments: 
We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors). We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
</li>
</ul>
            <h4>The payment processors we work with are:
</h4><ul>
            <li>
            Apple Store In-App Payments
            </li>
            <li>Their Privacy Policy can be viewed at https://www.apple.com/legal/privacy/en ww/

            </li>
            <li>
            Google Play In-App Payments
            </li>
            <li>
            Their Privacy Policy can be viewed at https://www.google.com/policies/privac

            </li>
            <li>
            PayPal / Braintree
            </li>
            <li>
            Their Privacy Policy can be viewed at https://www.paypal.com/webapps/mpp full
            </li>
            <li>
            Square
            </li>
            <li>
            Their Privacy Policy can be viewed at https://squareup.com/legal/privacy- no-account
            </li>
          </ul>
      
          <h3>Links to Other Sites</h3>
          <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
</p>
          <h3>Children Privacy</h3>
          <p>Our Service does not address anyone under the age of 18 (Children). We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
          <h3>Changes to This Privacy Policy</h3>
          <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the effective date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
          <h3>Contact Us!</h3>
          <p>If you have any questions about this Privacy Policy, please contact us:

By email: Rentalexoticsbeasts By visiting this page on our website: <a href="www.rentalexoticsbeasts.com">www.rentalexoticsbeasts.com</a> </p>
        </div>
      </div>
    </div>
  </div>
@endsection